name: yellow_group_flutterapp
description: "Flutter App Project for Yellow Group"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  go_router: ^13.0.0
  chopper: ^8.2.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.1
  dio: ^5.0.0
  shared_preferences: ^2.0.15
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  rxdart: ^0.28.0
  hive_ce: ^2.6.0
  hive_ce_flutter: ^2.1.0
  json_annotation: ^4.9.0
  logto_dart_sdk: ^3.0.0
  path_provider: ^2.1.0
  flutter_secure_storage: ^9.2.4
  oauth_chopper: 1.1.1
  url_launcher: ^6.3.2
  app_links: ^6.4.1
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  json_annotation: ^4.9.0
  build_runner: ^2.3.3
  chopper_generator: ^8.2.0
  freezed: ^2.4.1
  flutter_lints: ^5.0.0
  http: ^1.2.2
  hive_ce_generator: ^1.6.0


flutter:


  uses-material-design: true

  assets:
    - images/empty.jpg
    - images/homePageBackground.jpg
    - images/school_logo.png


fonts:
  - family: Merriweather
    fonts:
      - asset: fonts/Merriweather_24pt-Bold.ttf
      - asset: fonts/Merriweather_24pt-SemiBold.ttf
      - asset: fonts/Merriweather_24pt-Light.ttf
      - asset: fonts/Merriweather_24pt-SemiBoldItalic.ttf
      - asset: fonts/Merriweather_24pt-Italic.ttf
        weight: 600
      - asset: fonts/Merriweather_24pt-ExtraBold.ttf
        weight: 800

  - family: AverageSans
    fonts:
      -asset: fonts/AverageSans-Regular.ttf
      weight: 200


