name: yellow_group_flutterapp
description: "Flutter App Project for Yellow Group"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  go_router: ^13.0.0
  chopper: ^6.1.4
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.1
  analyzer: ^5.4.0
  dio: ^5.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  build_runner: ^2.3.3
  chopper_generator: ^6.0.3
  freezed: ^2.4.1
  flutter_lints: ^5.0.0
  http: ^1.2.2


flutter:


  uses-material-design: true

  assets:
    - images/empty.jpg
    - images/homePageBackground.jpg
#    - images/school_logo.png


fonts:
  - family: Merriweather
    fonts:
      - asset: fonts/Merriweather_24pt-Bold.ttf
      - asset: fonts/Merriweather_24pt-SemiBold.ttf
      - asset: fonts/Merriweather_24pt-Light.ttf
      - asset: fonts/Merriweather_24pt-SemiBoldItalic.ttf
      - asset: fonts/Merriweather_24pt-Italic.ttf
        weight: 600
      - asset: fonts/Merriweather_24pt-ExtraBold.ttf
        weight: 800

  - family: AverageSans
    fonts:
      -asset: fonts/AverageSans-Regular.ttf
      weight: 200


